export type Platform = 'youtube' | 'tiktok' | 'instagram'

export interface VideoItem {
  id: string
  platform: Platform
  title: string
  creator: string
  views: string
  /** 인기순 정렬용 숫자 조회수 */
  viewCount: number
  /** 최신 등록순 정렬용 ISO 날짜 */
  publishedAt: string
  /** CSS linear-gradient 정의 (썸네일 플레이스홀더) */
  gradientFrom: string
  gradientTo: string
  gradientVia?: string
  /** iframe embed URL */
  embedUrl: string
  /** 외부 플랫폼 원본 URL */
  originalUrl: string
  duration: string
}

export const MOCK_SONG = {
  title: 'Supernatural',
  artist: 'NewJeans',
}

export const MOCK_VIDEOS: VideoItem[] = [
  // ── YouTube Shorts (8) ──
  {
    id: 'yt-1',
    platform: 'youtube',
    title: '내 인생 최고의 순간 🎵 Supernatural 댄스 챌린지',
    creator: '@dancewithme_kr',
    views: '248만',
    viewCount: 2480000,
    publishedAt: '2024-07-15',
    gradientFrom: '#FF512F',
    gradientTo: '#DD2476',
    embedUrl: 'https://www.youtube.com/embed/wKCaFsdzBj4?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/wKCaFsdzBj4',
    duration: '0:23',
  },
  {
    id: 'yt-2',
    platform: 'youtube',
    title: 'Supernatural으로 만든 영상 ✨ 이게 진짜임',
    creator: '@moment.clips',
    views: '91만',
    viewCount: 910000,
    publishedAt: '2024-07-22',
    gradientFrom: '#1a1a2e',
    gradientTo: '#16213e',
    gradientVia: '#0f3460',
    embedUrl: 'https://www.youtube.com/embed/9bZkp7q19f0?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/9bZkp7q19f0',
    duration: '0:31',
  },
  {
    id: 'yt-3',
    platform: 'youtube',
    title: '뉴진스 Supernatural 커버댄스 | 이건 진짜 잘했다',
    creator: '@kpop_dance_studio',
    views: '53만',
    viewCount: 530000,
    publishedAt: '2024-08-01',
    gradientFrom: '#355C7D',
    gradientTo: '#6C5B7B',
    gradientVia: '#C06C84',
    embedUrl: 'https://www.youtube.com/embed/kJQP7kiw5Fk?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/kJQP7kiw5Fk',
    duration: '0:57',
  },
  {
    id: 'yt-4',
    platform: 'youtube',
    title: '오늘 하루 | Supernatural 브이로그',
    creator: '@dailylife_yj',
    views: '12만',
    viewCount: 120000,
    publishedAt: '2024-08-10',
    gradientFrom: '#11998e',
    gradientTo: '#38ef7d',
    embedUrl: 'https://www.youtube.com/embed/JGwWNGJdvx8?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/JGwWNGJdvx8',
    duration: '0:43',
  },
  {
    id: 'yt-5',
    platform: 'youtube',
    title: '🌸 봄 감성 Supernatural 편집 모음',
    creator: '@spring.edit',
    views: '320만',
    viewCount: 3200000,
    publishedAt: '2024-07-05',
    gradientFrom: '#f9a8d4',
    gradientTo: '#fbcfe8',
    gradientVia: '#e879f9',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    duration: '0:45',
  },
  {
    id: 'yt-6',
    platform: 'youtube',
    title: 'Supernatural 웨딩 영상에 씌우면 완벽함 💒',
    creator: '@wedding.clips_kr',
    views: '77만',
    viewCount: 770000,
    publishedAt: '2024-08-14',
    gradientFrom: '#fff1eb',
    gradientTo: '#ace0f9',
    embedUrl: 'https://www.youtube.com/embed/9bZkp7q19f0?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/9bZkp7q19f0',
    duration: '0:38',
  },
  {
    id: 'yt-7',
    platform: 'youtube',
    title: '뉴진스 MV 비하인드 장면들 모음 🎬',
    creator: '@kpop_behind',
    views: '190만',
    viewCount: 1900000,
    publishedAt: '2024-07-18',
    gradientFrom: '#667eea',
    gradientTo: '#764ba2',
    embedUrl: 'https://www.youtube.com/embed/kJQP7kiw5Fk?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/kJQP7kiw5Fk',
    duration: '0:52',
  },
  {
    id: 'yt-8',
    platform: 'youtube',
    title: 'Supernatural 역주행 시작..? 진짜 명곡임',
    creator: '@musiclover_jh',
    views: '34만',
    viewCount: 340000,
    publishedAt: '2024-09-03',
    gradientFrom: '#f7971e',
    gradientTo: '#ffd200',
    embedUrl: 'https://www.youtube.com/embed/JGwWNGJdvx8?autoplay=1&rel=0',
    originalUrl: 'https://www.youtube.com/shorts/JGwWNGJdvx8',
    duration: '0:27',
  },

  // ── TikTok (8) ──
  {
    id: 'tt-1',
    platform: 'tiktok',
    title: '#supernatural 이 노래 진짜 중독됨 ㅋㅋ',
    creator: '@jiwon._.vibe',
    views: '1.2M',
    viewCount: 1200000,
    publishedAt: '2024-07-10',
    gradientFrom: '#010101',
    gradientTo: '#3a1c71',
    gradientVia: '#d76d77',
    embedUrl: 'https://www.tiktok.com/embed/v2/7284523948123456789',
    originalUrl: 'https://www.tiktok.com/@jiwon._.vibe/video/7284523948123456789',
    duration: '0:17',
  },
  {
    id: 'tt-2',
    platform: 'tiktok',
    title: 'POV: 이 노래 들으면서 드라이브 가고 싶다',
    creator: '@roadtrip_kr',
    views: '876K',
    viewCount: 876000,
    publishedAt: '2024-07-25',
    gradientFrom: '#f093fb',
    gradientTo: '#f5576c',
    embedUrl: 'https://www.tiktok.com/embed/v2/7299887654321098765',
    originalUrl: 'https://www.tiktok.com/@roadtrip_kr/video/7299887654321098765',
    duration: '0:22',
  },
  {
    id: 'tt-3',
    platform: 'tiktok',
    title: 'supernatural 댄스 챌린지 1등 노림 🔥',
    creator: '@haeun_dance',
    views: '340K',
    viewCount: 340000,
    publishedAt: '2024-08-05',
    gradientFrom: '#4facfe',
    gradientTo: '#00f2fe',
    embedUrl: 'https://www.tiktok.com/embed/v2/7311234567890123456',
    originalUrl: 'https://www.tiktok.com/@haeun_dance/video/7311234567890123456',
    duration: '0:29',
  },
  {
    id: 'tt-4',
    platform: 'tiktok',
    title: '이 노래 들으면 자동으로 행복해짐 😊 #뉴진스',
    creator: '@feel_good_clips',
    views: '195K',
    viewCount: 195000,
    publishedAt: '2024-08-18',
    gradientFrom: '#fa709a',
    gradientTo: '#fee140',
    embedUrl: 'https://www.tiktok.com/embed/v2/7305678901234567890',
    originalUrl: 'https://www.tiktok.com/@feel_good_clips/video/7305678901234567890',
    duration: '0:15',
  },
  {
    id: 'tt-5',
    platform: 'tiktok',
    title: '새벽에 혼자 듣는 Supernatural... 감성 폭발 🌙',
    creator: '@latenight_mood',
    views: '2.1M',
    viewCount: 2100000,
    publishedAt: '2024-07-03',
    gradientFrom: '#0f0c29',
    gradientTo: '#302b63',
    gradientVia: '#24243e',
    embedUrl: 'https://www.tiktok.com/embed/v2/7280000000000000001',
    originalUrl: 'https://www.tiktok.com/@latenight_mood/video/7280000000000000001',
    duration: '0:19',
  },
  {
    id: 'tt-6',
    platform: 'tiktok',
    title: '강아지도 뉴진스 팬... Supernatural에 반응하는 멍이',
    creator: '@dog_daily_kr',
    views: '560K',
    viewCount: 560000,
    publishedAt: '2024-08-22',
    gradientFrom: '#d4a96a',
    gradientTo: '#c6773d',
    embedUrl: 'https://www.tiktok.com/embed/v2/7280000000000000002',
    originalUrl: 'https://www.tiktok.com/@dog_daily_kr/video/7280000000000000002',
    duration: '0:21',
  },
  {
    id: 'tt-7',
    platform: 'tiktok',
    title: '헬스장에서 supernatural 들으면 생기는 일',
    creator: '@gym_vibes_kr',
    views: '430K',
    viewCount: 430000,
    publishedAt: '2024-09-01',
    gradientFrom: '#1d976c',
    gradientTo: '#93f9b9',
    embedUrl: 'https://www.tiktok.com/embed/v2/7280000000000000003',
    originalUrl: 'https://www.tiktok.com/@gym_vibes_kr/video/7280000000000000003',
    duration: '0:31',
  },
  {
    id: 'tt-8',
    platform: 'tiktok',
    title: 'Supernatural 커버 보다가 눈물 나올 뻔 했잖아',
    creator: '@tearyeyes_kr',
    views: '88K',
    viewCount: 88000,
    publishedAt: '2024-09-08',
    gradientFrom: '#8360c3',
    gradientTo: '#2ebf91',
    embedUrl: 'https://www.tiktok.com/embed/v2/7280000000000000004',
    originalUrl: 'https://www.tiktok.com/@tearyeyes_kr/video/7280000000000000004',
    duration: '0:25',
  },

  // ── Instagram Reels (8) ──
  {
    id: 'ig-1',
    platform: 'instagram',
    title: '봄날 카페 브이로그 ☕ 이 노래랑 너무 잘 어울려',
    creator: '@cafe_moments',
    views: '52만',
    viewCount: 520000,
    publishedAt: '2024-07-12',
    gradientFrom: '#833ab4',
    gradientTo: '#fd1d1d',
    gradientVia: '#fcb045',
    embedUrl: 'https://www.instagram.com/reel/CzAbCdEfGhI/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzAbCdEfGhI/',
    duration: '0:35',
  },
  {
    id: 'ig-2',
    platform: 'instagram',
    title: '고양이 영상에 supernatural 넣으면 이렇게 된다',
    creator: '@cat_lover_seoul',
    views: '28만',
    viewCount: 280000,
    publishedAt: '2024-07-28',
    gradientFrom: '#a18cd1',
    gradientTo: '#fbc2eb',
    embedUrl: 'https://www.instagram.com/reel/CzXyZaBcDeF/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzXyZaBcDeF/',
    duration: '0:21',
  },
  {
    id: 'ig-3',
    platform: 'instagram',
    title: '한강 피크닉 🧺 영원히 이 순간이었으면',
    creator: '@seoulvibes_official',
    views: '14만',
    viewCount: 140000,
    publishedAt: '2024-08-08',
    gradientFrom: '#ffecd2',
    gradientTo: '#fcb69f',
    embedUrl: 'https://www.instagram.com/reel/CzMnOpQrStU/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzMnOpQrStU/',
    duration: '0:28',
  },
  {
    id: 'ig-4',
    platform: 'instagram',
    title: 'GRWM 이 노래 들으면서 준비하기 💄',
    creator: '@beauty_by_miso',
    views: '8.2만',
    viewCount: 82000,
    publishedAt: '2024-08-20',
    gradientFrom: '#2af598',
    gradientTo: '#009efd',
    embedUrl: 'https://www.instagram.com/reel/CzVwXyZaAbB/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzVwXyZaAbB/',
    duration: '0:44',
  },
  {
    id: 'ig-5',
    platform: 'instagram',
    title: '뉴진스 팬미팅 현장 🎤 Supernatural 라이브 소름',
    creator: '@kfan_live',
    views: '160만',
    viewCount: 1600000,
    publishedAt: '2024-07-08',
    gradientFrom: '#43e97b',
    gradientTo: '#38f9d7',
    embedUrl: 'https://www.instagram.com/reel/CzAbCdEfXxX/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzAbCdEfXxX/',
    duration: '0:48',
  },
  {
    id: 'ig-6',
    platform: 'instagram',
    title: '제주도 감성 여행기 🍊 BGM은 당연히 Supernatural',
    creator: '@jejuvibe',
    views: '41만',
    viewCount: 410000,
    publishedAt: '2024-08-30',
    gradientFrom: '#fd7043',
    gradientTo: '#ff8a65',
    gradientVia: '#ffb74d',
    embedUrl: 'https://www.instagram.com/reel/CzJejuIsland/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzJejuIsland/',
    duration: '0:55',
  },
  {
    id: 'ig-7',
    platform: 'instagram',
    title: '친구들이랑 Supernatural 커버 도전 ㅋㅋ 실패작',
    creator: '@oops_we_tried',
    views: '19만',
    viewCount: 190000,
    publishedAt: '2024-09-05',
    gradientFrom: '#ee9ca7',
    gradientTo: '#ffdde1',
    embedUrl: 'https://www.instagram.com/reel/CzFriendFail/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzFriendFail/',
    duration: '0:33',
  },
  {
    id: 'ig-8',
    platform: 'instagram',
    title: '새벽 한강 조깅 🎧 이 노래 들으면 3km는 가볍게',
    creator: '@morning_run_seoul',
    views: '7.8만',
    viewCount: 78000,
    publishedAt: '2024-09-10',
    gradientFrom: '#2c3e50',
    gradientTo: '#4ca1af',
    embedUrl: 'https://www.instagram.com/reel/CzMorningRun/embed/',
    originalUrl: 'https://www.instagram.com/reel/CzMorningRun/',
    duration: '0:40',
  },
]
