import type { Metadata, Viewport } from 'next'
import './globals.css'
import { WebviewProvider } from '@/components/WebviewProvider'
import { MixpanelProvider } from '@/components/MixpanelProvider'
import { CloseButton } from '@/components/ui/CloseButton'

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create-project',
}

/**
 * Force light mode only - Override device dark mode settings
 * This prevents Samsung Browser and other browsers from applying automatic dark mode
 * @see https://developer.samsung.com/internet/blog/en/2020/12/15/dark-mode-in-samsung-internet
 */
export const viewport: Viewport = {
  colorScheme: 'only light',
  themeColor: '#ffffff',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head>
      <body className="font-pretendard antialiased">
        <WebviewProvider />
        <MixpanelProvider />
        {children}
        <CloseButton />
      </body>
    </html>
  )
}
